apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobot-deployment
  labels:
    app: mobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 0
  template:
    metadata:
      labels:
        app: mobot
    spec:
      containers:
        - name: mobot
          image: andreyzuikov/mobot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: bot_token
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
